-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 004: Generated CVs
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.generated_cvs (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.users (id) on delete cascade,
  evaluation_id   uuid not null references public.evaluations (id) on delete cascade,

  cv_format       cv_format not null default 'chronological',

  -- Supabase Storage URL for the generated PDF
  pdf_url         text,
  pdf_generated_at timestamptz,

  -- Structured CV data (used to re-render HTML and regenerate PDF)
  cv_content      jsonb not null,
  -- cv_content schema: {
  --   personalDetails: { name, email, phone, location, linkedin },
  --   summary: string,
  --   workExperience: [{ title, company, dates, bullets[] }],
  --   skills: string[],
  --   education: [{ degree, institution, year }],
  --   tailoredFor: { jobTitle, company }
  -- }

  -- Optional ATS score (0–100, populated after PDF generation)
  ats_score       integer check (ats_score is null or ats_score between 0 and 100),

  created_at      timestamptz not null default now()
);

comment on table public.generated_cvs is
  'ATS-optimised CVs generated by Claude Sonnet. '
  'cv_content stores structured data; pdf_url points to Supabase Storage.';

comment on column public.generated_cvs.cv_content is
  'Structured CV data used to render HTML and regenerate PDF. '
  'Schema: personalDetails, summary, workExperience, skills, education, tailoredFor.';
